image: python:3.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - cp -f /usr/share/zoneinfo/Europe/Warsaw /etc/localtime
          - pip install -U flit pytest
          - python -m flit install
          - python -m pytest
